# Generated by Django 3.1.7 on 2021-03-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, unique=True)),
                ('gambar', models.CharField(blank=True, max_length=50, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=1024, null=True)),
                ('dd_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('npm', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('motivasi', models.CharField(blank=True, max_length=1024, null=True)),
                ('menjadi_pengurus', models.BooleanField(default=1)),
                ('minat1', models.CharField(blank=True, max_length=50, null=True)),
                ('minat2', models.CharField(blank=True, max_length=50, null=True)),
                ('hari', models.CharField(blank=True, max_length=50, null=True)),
                ('bahasa', models.CharField(blank=True, max_length=50, null=True)),
                ('harapan', models.CharField(blank=True, max_length=50, null=True)),
                ('dd_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
